### ISSUE TITLE
Goals for next GSoC milestone

### ISSUE THREAD

**Issue by m3nu** [invoice-x/invoicex-gui#3]
Here to clarify the expected outcome:

- [x] Fully working gui application for all three major OSs.
- [x] Can open and preview PDF files.
- [x] Views existing XML embeddings.
- [x] Allows to edit and save new XML embeddings in three major standards (factur-x, zugferd, UBL)
- [x] Complete XML embeddings from existing content (text and image PDFs) when an official `invoice2data` template is available for the issuer.
- [x] User can set custom template directory if issuer template isn't available yet.
- [x] Save edited PDF
- [x] Save XML metadata separately.
- [x] Developer documentation for new contributors. (includes instructions for development setup)
- [x] Staged development setup to avoid releasing unfinished versions to the public. E.g. dev + stable branches.
- [x] Tests that fail when any of the above described features fails.
- [x] Continuous integration setup to release new app packages after successful commits.
- [ ] Basic static website to describe features and link to releases. (can be hosted via Github pages for simplicity)
